name: build

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Install QEMU static binaries
      uses: docker/setup-qemu-action@v3

    - name: Configure Buildkit
      uses: docker/setup-buildx-action@v3

    - name: Checkout project
      uses: actions/checkout@v4

    - name: Authenticate with Quay.io
      uses: docker/login-action@v3
      if: ${{ github.event_name == 'push' }}
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build image
      id: push-step
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name == 'push' }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        sbom: true
        build-args: |-
          OVS_SERIES=3.1
          OVS_VERSION=3.1.0-55
        tags: |-
          quay.io/vexxhost/openvswitch:3.1.0-55atmosphere1

    - name: Install cosign
      if: ${{ github.event_name == 'push' }}
      uses: sigstore/cosign-installer@main

    - name: Sign the container image
      run: cosign sign --yes quay.io/vexxhost/openvswitch@${{ steps.push-step.outputs.digest }}
